### ISSUE TITLE
How to make cursor blinking on the focus input?

### ISSUE THREAD

**Issue by broodfusion** [andreaswilli/react-verification-input#11]
As title suggests, thanks

**Comment by andreaswilli** [comment]
Depends on what you mean by "blinking cursor":

- If you mean a native cursor: This is not possible since the visible part of the component is not acutally an input element.
- If you mean the selected field indicator: You can make it blink using a css animation like so:
```css
.character--selected {
  animation: blink 1s infinite;
}

@keyframes blink {
  0% {
    outline: orange 3px solid;
  }
  50% {
    outline: orange 3px solid;
  }
  51% {
    outline: none;
  }
  100% {
    outline: none;
  }
}
```
